app:
  name: Scrm STD Saas Api
  version: 1.0.0
  author: 张西海[mail@sniu.com]

spring:
  profiles:
    active: dev
  datasource:
    url: jdbc:mysql://localhost:3306/scrmstd
    username: username
    password: password

logging:
  level:
    root: WARN

mybatis:
  sql-print-to: console